language: ruby
sudo: false
rvm:
  - 2.1.2
script:
  - bundle exec rake test
  - bundle exec rubocop -V
  - bundle exec rubocop -F
addons:
  code_climate:
    repo_token:
      secure: eLzFNGAZk9F3FBXO+zCR11DxoPf7OH7mW8+4Ige4fifBgxGbwGeLEgF9YqALgNYd9MzR/UNcUR5+2Lyr2sPkmZzu9h81Bju3yi5dQICWdmldQQ26OBaeDloD4VHn9GLiunFyTFLQv8Z9GfAE1lRZYxLCS2nr+hi1hJOAazq+bhk=
